---
kind: pipeline
type: docker
name: build-dry-run
steps:
- name: build-dry-run
  image: plugins/docker
  settings:
    repo: ${DRONE_REPO_NAMESPACE}/${DRONE_REPO_NAME}
    dry_run: true
    purge: true
trigger:
  event:
    - pull_request

---
kind: pipeline
type: docker
name: push-development-build
steps:
- name: push-development-build
  image: plugins/docker
  settings:
    repo: ${DRONE_REPO_NAMESPACE}/${DRONE_REPO_NAME}
    tags: ${DRONE_BRANCH}
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    purge: true
trigger:
  branch:
    - development
  event:
    exclude:
      - pull_request
---
kind: pipeline
type: docker
name: push-latest-build
steps:
- name: push-latest-build
  image: plugins/docker
  settings:
    repo: ${DRONE_REPO_NAMESPACE}/${DRONE_REPO_NAME}
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    purge: true
trigger:
  branch:
    - master
  event:
    exclude:
      - pull_request
---
kind: pipeline
type: docker
name: push-feature-build
steps:
- name: push-feature-build
  image: plugins/docker
  settings:
    repo: ${DRONE_REPO_NAMESPACE}/${DRONE_REPO_NAME}
    tags: ${DRONE_BRANCH/\//-}
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    purge: true
trigger:
  branch:
    - feature/*
  event:
    exclude:
      - pull_request
---
kind: pipeline
type: docker
name: release
steps:
- name: push-tagged-build
  image: plugins/docker
  settings:
    repo: ${DRONE_REPO_NAMESPACE}/${DRONE_REPO_NAME}
    tags: ${DRONE_TAG##v}
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    purge: true
trigger:
  event:
    - tag

---
kind: secret
name: docker_username
data: t+SQXVB/ETHZWY8EV+VDJ7Lyivo+nI0mzkTMfcEGEaaSFBs2aaiFGa50VCc=
---
kind: secret
name: docker_password
data: WbACJLlbM1psou3UrG3iljDILxCo3r2P9zHqJKstZWbaaJXtJ6LynWDiDdruhI+oNVJb1pbVq239XipkjSYvtg==
---
kind: signature
hmac: b638dda0e056432929a0cf91f25d5b5173bf647ec945679a6974f2535a132863

...
